server:
  port: 8081

spring:
  application:
    name: building

    # database properties

  datasource:
    url: jdbc:postgresql://localhost:5432/BuildingManagementDB
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true