create table building
(
    identification_number    varchar(255) not null
        primary key,
    campus_location          integer,
    name                     varchar(255),
    number                   varchar(255),
    floors_id                bigint
        constraint fku9xo7pkvrlibgqqsyht6re4j
            references floors,
    geographical_location_id bigint
        constraint fk9fl82ms8qy2j2q7amdkuuog6k
            references geographical_location
);

alter table building
    owner to postgres;

INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5330', 2, 'Mensa und Studentenhaus', '01.12', 5330, 5330);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5334', 2, 'Englerstraße 14 (Wachter-Haus)', '01.80', 5334, 5334);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5335', 2, 'Kaiserstraße 14', '01.90', 5335, 5335);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5336', 2, 'Kronenstraße 30', '01.92', 5336, 5336);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5337', 2, 'Kronenstraße 32', '01.93', 5337, 5337);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5338', 2, 'Kronenstraße 34', '01.94', 5338, 5338);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5339', 2, 'Kaiserstraße 53', '01.95', 5339, 5339);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5340', 2, 'Waldhornstraße 27', '01.96', 5340, 5340);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5356', 2, 'Zoologisches Institut, Institutsgebäude', '07.01', 5356, 5356);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5357', 2, 'Zoologisches Institut, Lager', '07.02', 5357, 5357);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5358', 2, 'Zoologisches Institut, Container', '07.03', 5358, 5358);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5359', 2, 'Technologiefabrik', '07.21', 5359, 5359);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5364', 2, 'Verwaltungsgebäude, Hauptbau', '10.11', 5364, 5364);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5424', 2, 'Organische Chemie', '30.42', 5424, 5424);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5485', 1, 'Kolbenmaschinen, Motorenprüfstandshalle', '70.11', 5485, 5485);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5486', 1, 'Technikzentrale Ost', '70.12', 5486, 5486);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5487', 1, 'Containeranlage Motorenprüfstände', '70.13', 5487, 5487);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5488', 1, 'KFZ-und Motorenprüfstandshalle', '70.14', 5488, 5488);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5490', 1, 'Mackensen-Bau 16', '70.16', 5490, 5490);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5491', 1, 'Studentenwohnheim', '70.18', 5491, 5491);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5492', 1, 'KFZ-Schutzdach', '70.25', 5492, 5492);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5493', 1, 'Lagercontainer-Standfläche', '70.99', 5493, 5493);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-22112', 1, 'BW Pforte', '70.01', 22112, 22112);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-22113', 1, 'BW Kantine', '70.02', 22113, 22113);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-22150', 2, 'KIT-Bibliothek, Betriebshof', '30.52', 22150, 22150);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-22115', 1, 'Mackensen-Bau 04', '70.04', 22115, 22115);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-22119', 1, 'KFZ-Prüfhalle', '70.21', 22119, 22119);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-22122', 1, 'BW Kantine, Technikgebäude', '70.30', 22122, 22122);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-22123', 1, 'BW Dienstgebäude', '70.13A', 22123, 22123);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-22124', 1, 'BW Halle 14', '70.14A', 22124, 22124);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-24028', 1, 'Kolbenmaschinen, Tanklager', '70.15', 24028, 24028);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30119', 0, 'Regenhebeanlage', '0100', 30119, 30119);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30120', 0, 'Fortbildungszentrum für Technik und Umwelt [FTU]', '0101', 30120, 30120);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30121', 0, 'Meßmast [IMK]', '0102', 30121, 30121);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30122', 0, 'Bürogebäude [IMK]', '0103', 30122, 30122);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30125', 0, 'Meß-Container auf Meßgelände [IMK]', '0104/2', 30125, 30125);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30126', 0, 'Lager u. Wache Ausfahrt Süd [PKM]', '0121', 30126, 30126);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30127', 0, 'Toxikologisches Labor [MED]', '0122', 30127, 30127);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30128', 0, 'Büro- / Laborgebäude [SUM]', '0123', 30128, 30128);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30130', 0, 'Med. Abteilung u. Dekont. Passage [MED]', '0124', 30130, 30130);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30131', 0, 'Wache Süd (Tor 1) Ein/Ausfahrt [ASERV]', '0125', 30131, 30131);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30135', 0, 'Zentralgebäude', '0141', 30135, 30135);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30136', 0, 'Reprografie [SCC]', '0142', 30136, 30136);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30340', 0, 'Lagerraum [FM]', '0518', 30340, 30340);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5343', 3, 'Westhochschule - Bau 31', '06.31', 5343, 5343);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5344', 3, 'Westhochschule - Bau 32', '06.32', 5344, 5344);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5345', 3, 'Westhochschule - Bau 33', '06.33', 5345, 5345);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5346', 3, 'Westhochschule - Bau 34', '06.34', 5346, 5346);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5347', 3, 'Westhochschule - Bau 35', '06.35', 5347, 5347);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5348', 3, 'Westhochschule - Bau 36', '06.36', 5348, 5348);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5349', 3, 'Westhochschule - Bau 38', '06.38', 5349, 5349);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5350', 3, 'Westhochschule - Bau 40', '06.40', 5350, 5350);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5351', 3, 'Westhochschule - Bau 41', '06.41', 5351, 5351);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5352', 3, 'Westhochschule - Bau 42', '06.42', 5352, 5352);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5353', 3, 'Westhochschule - Bau 45', '06.45', 5353, 5353);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5354', 3, 'Westhochschule - Bau 46', '06.46', 5354, 5354);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5355', 3, 'Westhochschule - Bau 47', '06.47', 5355, 5355);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-22061', 3, 'Westhochschule - Schadstofflager', '06.50', 22061, 22061);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-26450', 3, 'St.-Barbara-Weg 5', '06.60', 26450, 26450);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-50399', 3, 'Klima-Teststand', '06.61', 50399, 50399);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5360', 2, 'Max Rubner-Institut (MRI), Gebäudeteil ZIT', '07.30', 5360, 5360);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5361', 2, 'Max Rubner-Institut (MRI), Gebäudeteil Technikum', '07.31', 5361, 5361);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5362', 2, 'Zentrum für Mediales Lernen (ZML)', '08.03', 5362, 5362);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5363', 2, 'Südwestdeut. Archiv für Architektur u. Ingenieurbau, Lager', '08.04', 5363, 5363);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5365', 2, 'Verwaltungsgebäude, Nordflügel', '10.12', 5365, 5365);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5366', 2, 'Hörsaalgebäude', '10.21', 5366, 5366);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5367', 2, 'Kollegiengebäude Maschinenbau II', '10.23', 5367, 5367);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5368', 2, 'Verkehrstechnisches Institut', '10.30', 5368, 5368);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5369', 2, 'Kavaliershäuschen West', '10.31', 5369, 5369);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5370', 2, 'Südwestdeutsches Archiv für Architektur u. Ingenieurbau', '10.32', 5370, 5370);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5371', 2, 'Kavaliershäuschen Ost', '10.33', 5371, 5371);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5372', 2, 'Südwestdeutsches Archiv für Architektur u. Ingenieurbau', '10.34', 5372, 5372);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5373', 2, 'Botanisches Institut', '10.40', 5373, 5373);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5374', 2, 'Kollegiengebäude Bauingenieure II', '10.50', 5374, 5374);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5375', 2, 'Versuchsanstalt Stahl/Holz/Steine, Prüfkammer+Materiallager', '10.61', 5375, 5375);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5376', 2, 'Fernleihe-Station', '10.62', 5376, 5376);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5377', 2, 'Windkanalhalle', '10.63', 5377, 5377);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-31080', 2, 'Sporthalle', '40.44', 31080, 31080);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-46880', 1, 'KFZ-Rollenprüfstand', '70.22', 46880, 46880);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-51640', 1, 'FhG-NAS Containerwerkstatt', '70.90', 51640, 51640);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-55359', 1, 'Bürogebäude', '70.03', 55359, 55359);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-56319', 1, 'MikroTribologie Centrum Campus Ost (µTC-CO)', '70.26', 56319, 56319);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-59900', 1, 'BHKW Heizstation', '70.28', 59900, 59900);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30480', 0, 'Gasflaschenlager [IKFT]', '0728', 30480, 30480);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30481', 0, 'Personalgebäude [IKFT]', '0729', 30481, 30481);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30482', 0, 'Fahrradhalle [IKFT]', '0730', 30482, 30482);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30484', 0, 'Technikum Biomassevergasung [IKFT]', '0732', 30484, 30484);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30485', 0, 'Lagerzelt ITC-CPV, nördl. Bau 724 [IKFT]', '0733', 30485, 30485);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30487', 0, 'Gasflaschenlager, Ostseite Bau 729 [IKFT]', '0735', 30487, 30487);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30488', 0, 'Lagerhalle, südl. Bau 721 [IKFT]', '0736', 30488, 30488);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30489', 0, 'Lagerzelt ITC-CPV, nördl. Bau 721', '0737', 30489, 30489);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30523', 0, '20 kV-Schalthaus [EnBW]', '0907', 30523, 30523);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30524', 0, 'Freiluftschaltanlage [EnBW]', '0908', 30524, 30524);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30528', 0, 'Bürogebäude [WAK]', '0913', 30528, 30528);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30541', 0, 'Hebeanlage (Sanitär) [WAK]', '0927', 30541, 30541);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5378', 2, 'Versuchsanstalt Stahl/Holz/Steine, Maschinengebäude', '10.64', 5378, 5378);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5379', 2, 'Versuchsanstalt Stahl/Holz/Steine, 50MN-Presse', '10.70', 5379, 5379);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5380', 2, 'Bauingenieure, Altes Bauingenieurgebäude', '10.81', 5380, 5380);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5381', 2, 'Windkanallabor (Kinzighalle)', '10.82', 5381, 5381);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5382', 2, 'Wasserwirtschaft und Kulturtechnik, Institutsgebäude', '10.83', 5382, 5382);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5383', 2, 'Theodor-Rehbock-Flußbaulaboratorium', '10.84', 5383, 5383);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5384', 2, 'Wasserwirtschaft und Kulturtechnik, Werkstattgebäude', '10.85', 5384, 5384);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5385', 2, 'Versuchsanstalt Stahl/Holz/Steine, Laborgebäude', '10.86', 5385, 5385);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5386', 2, 'Versuchsanstalt Stahl/Holz/Steine, Versuchshalle', '10.87', 5386, 5386);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5387', 2, 'Wasserwirtschaft und Kulturtechnik, Anbau', '10.88', 5387, 5387);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5388', 2, 'Wasserwirtschaft und Kulturtechnik, Bodenlabor', '10.89', 5388, 5388);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5389', 2, 'Maschinenbau, Altes Maschinenbaugebäude', '10.91', 5389, 5389);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5390', 2, 'wbk-Laborhalle', '10.92', 5390, 5390);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5391', 2, 'Fördertechnik / wbk, Laborhalle', '10.93', 5391, 5391);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5392', 2, 'Thermische Verfahrenstechnik, Laborhalle', '10.94', 5392, 5392);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5393', 2, 'Strömungslabor', '10.95', 5393, 5393);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5394', 2, 'Kolbenmaschinen / Kraftfahrzeugbau, Laborhalle', '10.96', 5394, 5394);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5396', 2, 'Kollegium am Schloss - Bau I', '20.11', 5396, 5396);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5397', 2, 'Kollegium am Schloss - Bau II', '20.12', 5397, 5397);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5398', 2, 'Kollegium am Schloss - Bau III', '20.13', 5398, 5398);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5399', 2, 'Kollegium am Schloss - Bau IV', '20.14', 5399, 5399);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5400', 2, 'Kollegiengebäude am Zirkel, Teil 1', '20.20', 5400, 5400);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5401', 2, 'Kollegiengebäude am Zirkel, Teil 2 (SCC)', '20.21', 5401, 5401);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5403', 2, 'Architekturgebäude', '20.40', 5403, 5403);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5405', 2, 'Winkelwohnblock E2', '20.50', 5405, 5405);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5406', 2, 'Winkelwohnblock E4', '20.51', 5406, 5406);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5407', 2, 'Winkelwohnblock E6', '20.52', 5407, 5407);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5408', 2, 'Winkelwohnblock NZ3', '20.53', 5408, 5408);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5409', 2, 'Winkelwohnblock NZ1', '20.54', 5409, 5409);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5410', 2, 'Nachrichtentechnik, Institutsgebäude', '30.10', 5410, 5410);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5411', 2, 'Nachrichtentechnik, Technische Station', '30.11', 5411, 5411);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5412', 2, 'Nachrichtentechnik, Meßplatz', '30.12', 5412, 5412);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5413', 2, 'Gerthsen-Hörsaalgebäude', '30.21', 5413, 5413);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5414', 2, 'Physik-Flachbau', '30.22', 5414, 5414);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5415', 2, 'Physik-Hochhaus', '30.23', 5415, 5415);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5417', 2, 'Biomedizinische Technik, Laborgebäude', '30.31', 5417, 5417);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5419', 2, 'Allgemeine Elektrotechnik', '30.33', 5419, 5419);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5420', 2, 'Lichttechnik', '30.34', 5420, 5420);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5421', 2, 'Hochspannungstechnik, Institutsgebäude', '30.35', 5421, 5421);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5422', 2, 'Hochspannungstechnik, Laborhalle', '30.36', 5422, 5422);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5423', 2, 'Chemie-Flachbau', '30.41', 5423, 5423);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5425', 2, 'Chemie-Turm I', '30.43', 5425, 5425);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5426', 2, 'Chemie-Turm II', '30.44', 5426, 5426);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5427', 2, 'Chemie-Turm III - Anorganische Chemie (AC)', '30.45', 5427, 5427);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5428', 2, 'Chemie-Hörsaalgebäude', '30.46', 5428, 5428);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5429', 2, 'KIT-Bibliothek Süd, Altbau', '30.50', 5429, 5429);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5430', 2, 'Therm.Strömungsmaschinen / Techn.Thermodynamik, Laborhalle', '30.60', 5430, 5430);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5431', 2, 'Therm.Strömungsmaschinen / Techn.Thermodynamik, Anbau', '30.61', 5431, 5431);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5432', 2, 'Mechanische Verfahrenstechnik und Mechanik, Institutsgebäude', '30.70', 5432, 5432);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5433', 2, 'Kinderbetreuung', '30.79', 5433, 5433);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5435', 2, 'Altes Stadiongebäude / Studentenzentrum AKK', '30.81', 5435, 5435);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5436', 2, 'Lösungsmittel- und Säurelager', '30.90', 5436, 5436);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5437', 2, 'Franz-Schnabel-Haus', '30.91', 5437, 5437);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5438', 2, 'Sonderabfall-Zwischenlager', '30.93', 5438, 5438);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5439', 2, 'Hörsaal-Gebäude am Forum (AUDIMAX)', '30.95', 5439, 5439);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5440', 2, 'Zentrum für Ost- und Mitteleuropa (ZOM)', '30.96', 5440, 5440);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5441', 2, 'Engler-Bunte-Institut (EBI) - Gas, Erdöl u. Kohle, Anbau', '40.02', 5441, 5441);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5442', 2, 'Engler-Bunte-Institut (EBI) - Wasserchemie, Anbau', '40.04', 5442, 5442);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5444', 2, 'Engler-Bunte-Institut (EBI) - Gas, Erdöl und Kohle', '40.12', 5444, 5444);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5445', 2, 'Engler-Bunte-Institut (EBI) - Feuerungstechnik', '40.13', 5445, 5445);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5446', 2, 'Engler-Bunte-Institut (EBI) - Wasserchemie', '40.14', 5446, 5446);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5447', 2, 'Engler-Bunte-Institut (EBI) - Werkstattgebäude', '40.15', 5447, 5447);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5448', 2, 'Kälteanlage, Zentrale', '40.16', 5448, 5448);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5449', 2, 'Abspannwerk (110 kV)', '40.17', 5449, 5449);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5451', 2, 'Engler-Bunte-Institut (EBI) - Technische Biologie', '40.19', 5451, 5451);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5452', 2, 'Boden- und Felsmechanik Bauteil 1, Institutsgebäude', '40.21', 5452, 5452);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5453', 2, 'Boden- und Felsmechanik Bauteil 2, Institutsgebäude', '40.22', 5453, 5453);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5454', 2, 'Boden- und Felsmechanik Bauteil 3, Institutsgebäude', '40.23', 5454, 5454);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5455', 2, 'Boden- und Felsmechanik Bauteil 4, Institutsgebäude', '40.24', 5455, 5455);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5456', 2, 'Boden- und Felsmechanik Bauteil 5, Institutsgebäude', '40.25', 5456, 5456);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5457', 2, 'Boden- und Felsmechanik Bauteil 6, Institutsgebäude', '40.26', 5457, 5457);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5458', 2, 'Boden- und Felsmechanik, Laborhalle', '40.27', 5458, 5458);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5459', 2, 'Prozeßrechentechnik und Robotik, Institutsgebäude', '40.28', 5459, 5459);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5460', 2, 'Maschinenbau / Bauingenieure, Versuchshalle', '40.29', 5460, 5460);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5461', 2, 'Technische Thermodynamik und Kältetechnik, Versuchshalle', '40.31', 5461, 5461);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5462', 2, 'Tech.Thermodyn.u.Kältetechn./Mess-u.Regelungstechn., Institutsgeb.', '40.32', 5462, 5462);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5463', 2, 'Mess- u. Regelungstechnik, Maschinenlaboratorium', '40.33', 5463, 5463);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5464', 2, 'Sport und Sportwissenschaft, Schwimmhalle, Institutsgebäude', '40.40', 5464, 5464);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5465', 2, 'Sport und Sportwissenschaft, Tennishaus "heimspiel."', '40.41', 5465, 5465);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5466', 2, 'Sport und Sportwissenschaft, Gerätehaus', '40.43', 5466, 5466);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5467', 2, 'Botanischer Garten, Labor- und Gewächshaus', '50.10', 5467, 5467);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5468', 2, 'Botanischer Garten, Gewächshaus', '50.12', 5468, 5468);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5470', 2, 'Ergänzungsbauten am Ring - Hauptgebäude', '50.20', 5470, 5470);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5471', 2, 'Ergänzungsbauten am Ring - ehem. Infektbau', '50.21', 5471, 5471);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5472', 2, 'Ergänzungsbauten am Ring - Studentenwohnheim Kolleg am Ring', '50.22', 5472, 5472);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5475', 2, 'Ergänzungsbauten am Ring - ehem. Verwaltung', '50.25', 5475, 5475);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5476', 2, 'Bauingenieure, Kollegiengebäude III', '50.31', 5476, 5476);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5477', 2, 'Bauingenieure, Prüfhalle', '50.32', 5477, 5477);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5478', 2, 'Bauingenieure / Maschinenbau, Versuchshalle', '50.33', 5478, 5478);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5479', 2, 'INFORMATIK, Kollegiengebäude am Fasanengarten', '50.34', 5479, 5479);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5480', 2, 'Fasanengarten-Hörsaalgebäude', '50.35', 5480, 5480);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5481', 2, 'wbk - Versuchs- und Bürogebäude', '50.36', 5481, 5481);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5482', 2, 'Fördertechnik u. Logistiksysteme, Institutsgeb. mit Laborhalle', '50.38', 5482, 5482);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5483', 2, 'Forschungszentrum Umwelt (FZU)', '50.40', 5483, 5483);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5484', 2, 'Allgemeines Verfügungsgebäude (AVG) mit Rundbau', '50.41', 5484, 5484);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5516', 2, 'Elektrotechnisches Institut (ETI)', '11.10', 5516, 5516);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5518', 2, 'Engler-Villa', '11.20', 5518, 5518);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5519', 2, 'Chemische Technik', '11.21', 5519, 5519);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5520', 2, 'Zentrale Betriebstechnik (ZBT)', '11.22', 5520, 5520);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5521', 2, 'Neue Chemische Technik + Polymer-Institut', '11.23', 5521, 5521);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-5523', 2, 'Kollegiengebäude am Ehrenhof', '11.40', 5523, 5523);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-20630', 2, 'Gastdozentenhaus (GDH)', '01.52', 20630, 20630);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-20651', 2, 'KIT-Bibliothek Süd, Neubau', '30.51', 20651, 20651);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-20830', 2, 'Pförtnerhaus, Nord-Einfahrt', '40.39', 20830, 20830);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-21230', 2, 'Forschungszentrum Informatik (FZI)', '07.11', 21230, 21230);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-22064', 2, 'Kondensatrückspeisestation (ehemals)', '20.42', 22064, 22064);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-22065', 2, 'Gebäude für Flüssigstoffe', '30.47', 22065, 22065);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-22066', 2, 'Wasserrückkühlanlage', '30.62', 22066, 22066);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-22170', 2, 'Kreuzstraße 11', '05.01', 22170, 22170);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-22250', 2, 'Fahrrad-Garage (für Geb.11.2x)', '11.24', 22250, 22250);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-22251', 2, 'Gaslager', '40.34', 22251, 22251);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-22930', 2, 'Gerätehaus Gebäudebetriebssdienst', '30.82', 22930, 22930);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-23791', 2, 'Vincenz-Prießnitz-Straße 1', '07.07', 23791, 23791);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-23792', 2, 'Vincenz-Prießnitz-Straße 3', '07.08', 23792, 23792);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-24451', 2, 'Physik-Werkstattgebäude', '30.24', 24451, 24451);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-24590', 2, 'Emmy-Noether-Straße 11', '07.40', 24590, 24590);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-24670', 2, 'Centrum für Funktionelle Nanostrukturen (CFN)', '30.25', 24670, 24670);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-26210', 2, 'Emmy-Noether-Straße 10', '07.39', 26210, 26210);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-26270', 2, 'Pförtnerhaus, Ring-Einfahrt', '50.29', 26270, 26270);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-26970', 2, 'Start-up Pavillon', '30.29', 26970, 26970);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-27731', 2, 'Fritz-Erler-Straße 23 (Röser-Haus)', '01.86', 27731, 27731);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-27732', 2, 'Fritz-Erler-Straße 1-3 (Zähringer-Haus)', '01.85', 27732, 27732);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-29779', 2, 'Münze KA, östl. Nebengebäude', '09.01', 29779, 29779);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-29780', 2, 'Münze KA, Hauptgebäude', '09.02', 29780, 29780);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-29860', 2, 'Münze KA, westl. Nebengebäude', '09.06', 29860, 29860);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-46819', 2, 'Außenbauwerk für Geb.20.20', '20.22', 46819, 46819);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-47539', 2, 'Rüppurrer Straße 1a (PSD)', '01.87', 47539, 47539);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-47599', 2, 'KinderUniversum', '50.26', 47599, 47599);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-47639', 2, 'Kapellenstraße 17 (LGL)', '05.02', 47639, 47639);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-50519', 2, 'Materialwissenschaftliches Zentrum für Energiesysteme (MZE) (in Bau)', '30.48', 50519, 50519);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-50520', 2, 'MikroTribologie Centrum (µTC) (in Bau)', '30.49', 50520, 50520);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-50639', 2, 'Kaiserstraße 89-93 (Allianz-Gebäude)', '05.20', 50639, 50639);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-51359', 2, 'Lernzentrum 2012', '30.28', 51359, 51359);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-51679', 2, 'Präsidium (Adolf-Würth-Gebäude)', '11.30', 51679, 51679);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-54379', 2, 'Kollegiengebäude Mathematik', '20.30', 54379, 54379);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-57579', 2, 'International Department', '02.95', 57579, 57579);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-59129', 2, 'Mensa', '01.13', 59129, 59129);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30137', 0, 'Rechenzentrum [SCC]', '0144', 30137, 30137);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30138', 0, 'Casino [ASERV]', '0145', 30138, 30138);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30139', 0, 'Wasserwerk Süd, (Rückspülbecken) [FM]', '0151', 30139, 30139);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30140', 0, 'ANKA Nutzerhaus [ISS]', '0152', 30140, 30140);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30141', 0, 'Dienstleistungsgebäude  [BBBank]', '0210', 30141, 30141);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30142', 0, 'ehemalige Kantine [ASERV]', '0211', 30142, 30142);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30143', 0, 'Getränkeleergutlager [ASERV]', '0212', 30143, 30143);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30144', 0, 'KiTa "nanos!"', '0213', 30144, 30144);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30145', 0, 'Garagen, westl. Tankstelle [ASERV]', '0220', 30145, 30145);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30146', 0, 'Anmeldung, Hauptwache [ASERV]', '0221', 30146, 30146);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30147', 0, 'Telefonzentrale [ASERV]', '0222', 30147, 30147);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30148', 0, 'Laborgebäude Fischzucht [ITG]', '0223', 30148, 30148);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30149', 0, 'Garagen Fahrdienst [ASERV]', '0224', 30149, 30149);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30150', 0, 'KFZ-Werkstatt [ASERV]', '0225', 30150, 30150);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30151', 0, 'Garagen Fahrdienst, Büroräume [ASERV]', '0226', 30151, 30151);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30152', 0, 'Garagen Fahrdienst [ASERV]', '0227', 30152, 30152);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30153', 0, 'Pumpwerk Süd, Zerkleinerungsanlage [FM]', '0228', 30153, 30153);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30154', 0, 'Materiallager [EVM]', '0229', 30154, 30154);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30155', 0, 'Technikumshalle (Mikroelektronik) [IPE]', '0230', 30155, 30155);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30156', 0, 'Chemikalienlager [EVM]', '0231', 30156, 30156);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30157', 0, 'Schneidhalle [EVM]', '0232', 30157, 30157);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30158', 0, 'Güterkontrolle (Tor 10) [ASERV]', '0234', 30158, 30158);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30159', 0, 'Lehrwerkstätten II - Betriebliche Ausbildung [PEBA]', '0235', 30159, 30159);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30161', 0, 'Lehrwerkstätten I [PEBA]', '0237', 30161, 30161);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30166', 0, 'Büro-/Laborgebäude [IPE]', '0242', 30166, 30166);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30167', 0, 'Technik-Haus [TEC]', '0243', 30167, 30167);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30169', 0, 'Werkstattgebäude mit Technikumshalle [TEC]', '0245', 30169, 30169);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30170', 0, 'Tankstelle, Garagen [IG]', '0246', 30170, 30170);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30171', 0, 'Abwassersammelstation [IPE]', '0247', 30171, 30171);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30172', 0, 'Lager und Werkstattgebäude [IKP]', '0248', 30172, 30172);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30173', 0, 'Entrostungsanlage [IKP]', '0249', 30173, 30173);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30175', 0, 'Lagerhalle für Holz [TEC]', '0251', 30175, 30175);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30176', 0, 'Bauhof - Lagerhalle [FM]', '0252', 30176, 30176);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30178', 0, 'Bauhof - Verwaltung/Personalgebäude [FM]', '0253', 30178, 30178);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30179', 0, 'Bauhof - Werkhalle [FM]', '0254', 30179, 30179);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30180', 0, 'Fernheizwerk mit Blockheizkraftwerk [FM]', '0255', 30180, 30180);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30181', 0, 'Bürogebäude [EVM]', '0256', 30181, 30181);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30182', 0, 'Prüfhalle [ITEP]', '0257', 30182, 30182);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30183', 0, 'Gasübergabestation [FM]', '0258', 30183, 30183);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30184', 0, 'Dieselhaus [FM]', '0259', 30184, 30184);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30185', 0, 'Lagergebäude, westl. Bau 255', '0260/1', 30185, 30185);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30188', 0, 'Technikumshalle [ITEP, IKET]', '0272', 30188, 30188);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30192', 0, 'Anbau (elektrische Anlagen Schlosserei) [ITEP]', '0274', 30192, 30192);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30193', 0, 'Lagerhalle und Technikumshalle [ITEP, IKET]', '0276', 30193, 30193);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30194', 0, 'Chemiehebewerk [FM]', '0277', 30194, 30194);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30195', 0, 'Gasflaschenlager [IKET]', '0278', 30195, 30195);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30196', 0, 'Technikzentrale Maskenlabor [IMT]', '0300', 30196, 30196);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30197', 0, 'Büro-/Laborgebäude u. Technikumshalle [IMT]', '0301', 30197, 30197);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30199', 0, 'KIT-Bibliothek Nord', '0303', 30199, 30199);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30200', 0, 'Büro-/Laborgebäude [ITG]', '0304', 30200, 30200);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30201', 0, 'Bürogebäude [ITG]', '0305', 30201, 30201);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30202', 0, 'Abwassersammelstation [FM]', '0306', 30202, 30202);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30203', 0, 'Erweiterung Arbeitsräume [IMT]', '0307', 30203, 30203);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30205', 0, 'Laborgebäude (Reinraum) [IMT]', '0309', 30205, 30205);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30206', 0, 'Erweiterung Arbeitsräume [IMT]', '0310', 30206, 30206);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30209', 0, 'Büro- und Werkstattgebäude [ITG]', '0313', 30209, 30209);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30210', 0, 'Gasflaschenlager [IMT]', '0314', 30210, 30210);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30211', 0, 'Feuerwache [ASERV]', '0315', 30211, 30211);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30212', 0, 'Bürogebäude [ASERV]', '0316', 30212, 30212);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30213', 0, 'Tierställe, Technikzentrale [ITG]', '0317', 30213, 30213);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30214', 0, 'Gefahrstofflager-Boxen [IMT]', '0318', 30214, 30214);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30217', 0, 'Büro- / Laborgebäude [IMT]', '0321', 30217, 30217);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30218', 0, 'Laborgebäude [IMK]', '0322', 30218, 30218);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30220', 0, 'Laborgebäude [IKFT]', '0324', 30220, 30220);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30221', 0, 'Bürogebäude [IMK]', '0326', 30221, 30221);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30222', 0, 'Büro und Laborgebäude [IMK]', '0327', 30222, 30222);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30223', 0, 'Gasflaschenlager [IMK]', '0328', 30223, 30223);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30224', 0, 'Verfügungsgebäude (Containeranlage) [ISS]', '0329', 30224, 30224);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30225', 0, 'Büro- / Laborgebäude u. Technikumshalle [IFG]', '0330', 30225, 30225);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30226', 0, 'Regenhebewerk [FM]', '0331', 30226, 30226);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30230', 0, 'Verfügungsgebäude [ITG]', '0341', 30230, 30230);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30231', 0, 'Abwassersammelstation [FM]', '0343', 30231, 30231);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30232', 0, 'Gasflaschenlager, Süd-West Bau 351/8 [ZAG]', '0344', 30232, 30232);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30233', 0, 'Bürogebäude [ISS]', '0345', 30233, 30233);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30234', 0, 'Gasflaschen- u. Gerätelager [ITG]', '0347', 30234, 30234);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30235', 0, 'Technikumshalle ANKA [ISS]', '0348', 30235, 30235);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30236', 0, 'Kälteanlage ANKA [ISS]', '0349', 30236, 30236);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30237', 0, 'Laborgebäude ZAG [ISS]', '0351', 30237, 30237);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30238', 0, 'Zyklotron Laborgebäude [ISS]', '0352', 30238, 30238);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30247', 0, 'Abwassersammelstation [FM]', '0400', 30247, 30247);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30248', 0, 'Büro-/Laborgebäude u. Technikumshalle [ITEP, IKP]', '0401', 30248, 30248);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30250', 0, 'Bürogebäude [IKP]', '0402', 30250, 30250);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30251', 0, 'Laborgebäude [ITC]', '0403', 30251, 30251);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30252', 0, 'Technikumshalle/TAMARA [ITC]', '0404', 30252, 30252);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30254', 0, 'Abwassersammelstation [FM]', '0405', 30254, 30254);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30255', 0, 'Technikumshalle [ITEP]', '0406', 30255, 30255);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30262', 0, 'Kälteanlage [ITEP]', '0406G', 30262, 30262);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30263', 0, 'Gaslager TIMO 1 [ITEP]', '0406H', 30263, 30263);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30264', 0, 'Werkstattgebäude [ITC]', '0407', 30264, 30264);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30265', 0, 'Kaltverformung [ITEP]', '0408', 30265, 30265);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30266', 0, 'Kälteanlage [ITEP]', '0409', 30266, 30266);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30267', 0, 'Bürogebäude [ITEP]', '0410', 30267, 30267);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30268', 0, 'Leichtbauhalle [ITEP]', '0411', 30268, 30268);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30269', 0, 'Kühltürme (2 x 6 MW) [IKET]', '0412', 30269, 30269);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30270', 0, 'Prüfstandhalle [IKET]', '0413', 30270, 30270);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30271', 0, 'Gasflaschenlager', '0413A', 30271, 30271);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30273', 0, 'Laboratorium [IKET]', '0415', 30273, 30273);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30274', 0, 'Bürogebäude [ITEP]', '0416', 30274, 30274);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30275', 0, 'Bürogebäude [ITEP]', '0417', 30275, 30275);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30276', 0, 'Bürogebäude [ITEP]', '0418', 30276, 30276);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30277', 0, 'Bürogebäude [IKET]', '0419', 30277, 30277);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30278', 0, 'Bürogebäude [IKET]', '0420', 30278, 30278);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30279', 0, 'Büro- / Laborgebäude [IHM]', '0421', 30279, 30279);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30280', 0, 'Werkstattgebäude [IHM]', '0422', 30280, 30280);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30281', 0, 'Technikumshalle [IHM]', '0423', 30281, 30281);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30283', 0, 'Werkstattgebäude [IFP]', '0424', 30283, 30283);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30285', 0, 'Büro- / Laborgebäude [IFP]', '0425', 30285, 30285);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30286', 0, 'Van-de-Graaff Beschleuniger [IFP]', '0426', 30286, 30286);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30287', 0, 'Schmutzwasser-Hebeanlage YV-C3 [FM]', '0427', 30287, 30287);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30288', 0, 'Versuchsstände [IKET]', '0428', 30288, 30288);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30290', 0, 'Bürogebäude [ITC]', '0430', 30290, 30290);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30291', 0, 'Garage, südl. Bau 442', '0431', 30291, 30291);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30293', 0, 'Bürogebäude [NUKLEAR]', '0433', 30293, 30293);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30294', 0, 'Technikumshalle [IFP]', '0434', 30294, 30294);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30295', 0, 'Büro- / Laborgebäude [IMK]', '0435', 30295, 30295);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30296', 0, 'Bürogebäude [PTKA]', '0436', 30296, 30296);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30298', 0, 'Regenrückhaltebecken mit Hebewerk [FM]', '0437', 30298, 30298);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30299', 0, 'Bürogebäude [PTKA]', '0438', 30299, 30299);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30300', 0, 'Büro- / Laborgebäude [SUM]', '0439', 30300, 30300);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30301', 0, 'Bürogebäude [STN]', '0440', 30301, 30301);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30302', 0, 'Rechenzentrum [SCC]', '0441', 30302, 30302);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30303', 0, 'Büro-Containeranlage', '0441/1', 30303, 30303);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30304', 0, 'Erweiterung Rechenzentrum [SCC]', '0442', 30304, 30304);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30305', 0, 'Verteilerstation [FM]', '0443', 30305, 30305);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30307', 0, 'Büro- / Laborgebäude [IAI]', '0445', 30307, 30307);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30308', 0, 'Gaslager u. Garagen', '0446', 30308, 30308);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30309', 0, 'LAN-Verteilerstation', '0447', 30309, 30309);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30310', 0, 'Bürogebäude [IMK]', '0448', 30310, 30310);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30311', 0, 'Rechenzentrum u. Institutsgebäude [SCC]', '0449', 30311, 30311);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30312', 0, 'Netzersatzanlage Tritiumlabor [ITEP]', '0450', 30312, 30312);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30313', 0, 'Bürogebäude [ITEP]', '0451', 30313, 30313);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30314', 0, 'Tritiumlabor [ITEP]', '0452', 30314, 30314);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30315', 0, 'Versuchshalle', '0453', 30315, 30315);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30316', 0, 'SUAK-Bunker', '0454', 30316, 30316);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30318', 0, 'Technikgebäude KATRIN [IKP]', '0456', 30318, 30318);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30319', 0, 'Transporthalle KATRIN, Bau 457 [IKP]', '0457', 30319, 30319);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30322', 0, 'Spektrometerhalle KATRIN [IKP]', '0460', 30322, 30322);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30323', 0, 'Monitorgebäude KATRIN [IKP]', '0461', 30323, 30323);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30324', 0, 'Versorgung Spektrometerhalle KATRIN [IKP]', '0462', 30324, 30324);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30325', 0, 'Kaltwasserversorgung KATRIN [IKP]', '0464', 30325, 30325);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30326', 0, 'Gasversorgung KATRIN West [IKP]', '0466', 30326, 30326);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30327', 0, 'Sanitärcontainer KATRIN [IKP]', '0467', 30327, 30327);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30331', 0, 'HELOKA-Techikhalle [INR]', '0508', 30331, 30331);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30332', 0, 'Abwasserüberwachungszentrale [FM]', '0510', 30332, 30332);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30333', 0, 'Kläranlagen für Sanitärabwasser [FM]', '0511', 30333, 30333);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30334', 0, 'Betriebsgebäude und Dosierstation [FM]', '0512', 30334, 30334);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30335', 0, 'Chemiekläranlage (Behandlungsstufe und Speicherbec [FM]', '0513', 30335, 30335);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30336', 0, 'Chemiekläranlage (Pumpwerk 1, Schlammbehandlungsan [FM]', '0514', 30336, 30336);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30337', 0, 'Wasserlabor [FM]', '0515', 30337, 30337);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30338', 0, 'Chemiekläranlage (Eingangsstufe) [FM]', '0516', 30338, 30338);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30339', 0, 'Sanitärkläranlage (Endbecken und Pumpwerk 2) [FM]', '0517', 30339, 30339);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30342', 0, 'Regenrückhaltebecken und Hebewerk [FM]', '0520', 30342, 30342);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30343', 0, 'Büro- / Laborgebäude [INR]', '0521', 30343, 30343);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30344', 0, 'Technikumshalle [INR]', '0522', 30344, 30344);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30346', 0, 'Lager-/Leichtbauhalle (in Planung)', '0525', 30346, 30346);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30358', 0, 'Regenhebewerk, im HDB-Areal, südl. Bau 9657 [FM]', '0540', 30358, 30358);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30359', 0, 'Werkstattgebäude (-Betrieb) [FM]', '0541', 30359, 30359);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30360', 0, 'Abwassersammelstation (stillgelegt) [FM]', '0542', 30360, 30360);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30362', 0, 'Betriebswerkstatt [FM]', '0544', 30362, 30362);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30367', 0, 'Technikumshalle [ITC]', '0549', 30367, 30367);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30371', 0, 'Regenhebewerk [FM]', '0554', 30371, 30371);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30389', 0, 'Werkstattgebäude [IAM]', '0572', 30389, 30389);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30390', 0, 'Laborgebäude [IAM]', '0573', 30390, 30390);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30391', 0, 'Laborgebäude / Erweiterung [IAM]', '0574', 30391, 30391);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30392', 0, 'Bürogebäude [IAM]', '0575', 30392, 30392);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30396', 0, 'Büro- / Laborgebäude [IBG]', '0601', 30396, 30396);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30397', 0, 'Versuchshalle [IKP]', '0602', 30397, 30397);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30398', 0, 'Schweißwerkstatt [IBG]', '0603', 30398, 30398);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30399', 0, 'Abfallzwischenlager [FM]', '0604', 30399, 30399);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30400', 0, 'Büro- / Laborgebäude [IMVT]', '0605', 30400, 30400);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30401', 0, 'Büro- / Laborgebäude [IMVT]', '0606', 30401, 30401);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30403', 0, 'Experimentierhalle [IKET]', '0608', 30403, 30403);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30404', 0, 'Gasflaschenlager, nördl. Bau 608 [IKET]', '0608a', 30404, 30404);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30405', 0, 'LAN-Verteilerstation', '0609', 30405, 30405);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30406', 0, 'Verteilerstation [FM]', '0610', 30406, 30406);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30408', 0, 'Kältezentrale (in Planung)', '0612', 30408, 30408);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30409', 0, 'Wasserhochbehälter / Fortluftkamin [FM]', '0614', 30409, 30409);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30410', 0, 'Vollentsalzungsanlage [FM]', '0615', 30410, 30410);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30411', 0, 'Pumpwerk Nord I (Sanitär)', '0616', 30411, 30411);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30412', 0, 'LCF-Halle [IAM]', '0618', 30412, 30412);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30413', 0, 'Gewächshaus [IFG]', '0620', 30413, 30413);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30414', 0, 'Gewächshaus', '0622', 30414, 30414);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30415', 0, 'Technikumshalle [ISS]', '0629', 30415, 30415);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30416', 0, 'Büro-/Laborgebäude und Technikumshalle [IHM]', '0630', 30416, 30416);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30417', 0, 'Versorgungszentrale [IHM]', '0631', 30417, 30417);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30419', 0, 'Abfalldepot [INT]', '0638', 30419, 30419);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30420', 0, 'Chemikalienlager [INT]', '0639', 30420, 30420);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30421', 0, 'Institutsgebäude  [INT]', '0640', 30421, 30421);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30422', 0, 'Thermit-Versuchshalle [IKET]', '0650', 30422, 30422);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30423', 0, 'Versuchsgebäude HELOKA [INR]', '0660', 30423, 30423);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30424', 0, 'Seism. Beobachtungsstation (200 m-Bohrung)', '0661', 30424, 30424);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30426', 0, 'Experimentiergebäude (bioliq) [ITC]', '0670', 30426, 30426);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30436', 0, 'Büro- / Laborgebäude [IAM]', '0681', 30436, 30436);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30437', 0, 'Bürogebäude [IAM]', '0682', 30437, 30437);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30438', 0, 'Gasflaschenlager [IAM]', '0683', 30438, 30438);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30442', 0, 'Pumpwerk Nord II (Sanitär) [FM]', '0685', 30442, 30442);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30443', 0, 'Elektrozentrale Nord [EnBW, ITC]', '0686', 30443, 30443);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30444', 0, 'Laborgebäude für Analytik [IAM]', '0688', 30444, 30444);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30445', 0, 'Autoklav [IAM]', '0689', 30445, 30445);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30447', 0, 'Büro-/Laborgebäude u. Technikumshalle [ITC]', '0691', 30447, 30447);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30448', 0, 'Gasflaschenlager [ITC]', '0692', 30448, 30448);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30449', 0, 'Sozialgebäude [ITC]', '0693', 30449, 30449);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30450', 0, 'Büro- / Laborgebäude [IMF]', '0695', 30450, 30450);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30451', 0, 'Büro- / Laborgebäude [IAM]', '0696', 30451, 30451);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30453', 0, 'Heiße Zellen [IAM]', '0701', 30453, 30453);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30456', 0, 'Betriebswäscherei [ASERV]', '0705', 30456, 30456);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30457', 0, 'Abwassersammelstation [FM]', '0706', 30457, 30457);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30458', 0, 'Bürogebäude (Hightech-Inkubator) [IMA]', '0707', 30458, 30458);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30459', 0, 'Heiße Zellen [IAM]', '0708', 30459, 30459);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30460', 0, 'Abluftschornstein 2 [IAM]', '0709', 30460, 30460);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30461', 0, 'Regenhebewerk und Rückhaltebecken [FM]', '0711', 30461, 30461);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30462', 0, 'Büro-/Laborgebäude und Technikumshalle [INE]', '0712', 30462, 30462);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30464', 0, 'Büro-/Laborgebäude und Technikumshalle [INE]', '0714', 30464, 30464);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30466', 0, 'Leichtbauhalle Lager [INE]', '0716', 30466, 30466);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30467', 0, 'Büro- und Laborgebäude (Hightech-Inkubator) [IMA, INT]', '0717', 30467, 30467);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30468', 0, 'Leichtbauhalle [INE]', '0718', 30468, 30468);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30469', 0, 'Chemielager [INT]', '0719', 30469, 30469);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30470', 0, 'Celitement-Gebäude', '0720', 30470, 30470);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30471', 0, 'Laborgebäude [IKFT]', '0721', 30471, 30471);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30472', 0, 'Abluftschornstein [IKFT]', '0722', 30472, 30472);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30473', 0, 'Versorgungszentrale [IKFT]', '0723', 30473, 30473);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30474', 0, 'Technikumshalle [IKFT]', '0724', 30474, 30474);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30475', 0, 'Erweiterung Laborgebäude [IKFT]', '0725', 30475, 30475);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30476', 0, 'Elektronik-Werkstatt [IKFT]', '0726', 30476, 30476);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30477', 0, 'Bürogebäude [IKFT]', '0727', 30477, 30477);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30546', 0, 'Eichhalle und Erweiterung [ASERV]', '5131', 30546, 30546);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30547', 0, 'Bürobaracke [PEBA]', '5252', 30547, 30547);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30548', 0, 'Bauhof - Lagerbaracke [FM]', '5254', 30548, 30548);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30549', 0, 'Meßhütte West', '5311', 30549, 30549);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30550', 0, 'Laborbaracke [IKP]', '5402', 30550, 30550);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30551', 0, 'Leichtbauhalle [ITC]', '5404', 30551, 30551);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30553', 0, 'Druckluftversorgung [FM]', '5523', 30553, 30553);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30557', 0, 'Halle [ITC, IFG]', '5621', 30557, 30557);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30559', 0, 'Meßhütte Nord [SUM]', '5812', 30559, 30559);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30560', 0, 'Meßhütte Nordost [SUM]', '5813', 30560, 30560);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30720', 0, 'Wache Nord (Tor 7) [ASERV]', '1600', 30720, 30720);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30723', 0, 'Meßstelle Forsthaus/Werkswohnung', '2093', 30723, 30723);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30729', 0, 'Ostendorf-Haus', '0191', 30729, 30729);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30731', 0, 'Gästehaus Mühlburger Tor', '0193', 30731, 30731);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30733', 0, 'Gastdozentenhaus Karlsruhe', '0197', 30733, 30733);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30754', 0, 'Container südwestl. Bau 549 [ITC]', '9629', 30754, 30754);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30786', 0, 'Büro-Containeranlage südl. Bau 758 [ISS]', '9670', 30786, 30786);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-30788', 0, 'Fremdfirmendepot', '9800', 30788, 30788);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-31009', 0, 'KIT Campus-Nord Bahnhof', '9092', 31009, 31009);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-32179', 0, 'Bürogebäude ITAS, Karlstraße 11 [ITAS]', '3300', 32179, 32179);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-32241', 0, 'Antenne TETRA-Netz, Höhe SF1', '0263', 32241, 32241);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-32279', 0, 'Haupteinfahrt Süd', '9030', 32279, 32279);
INSERT INTO public.building (identification_number, campus_location, name, number, floors_id, geographical_location_id) VALUES ('b-32299', 0, '1 Garage', '0312A', 32299, 32299);
