openapi: 3.0.0
info:
  version: '1'
  title: API for Building
  description: REST API provided by Domain Microservice BuildingManagement.
servers:
  # Added by API Auto Mocking Plugin
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Smart_Campus/Building_API/1
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Smart_Campus/Building_Management/1

paths:
  /buildings:
    get:
      tags:
        - Buildings
      summary: Get information about all buildings
      responses:
        200:
          $ref: '#/components/responses/building'
        400:
          description: invalid bin format.
        401:
          description: unauthorized access.
        404:
          description: building not found.
    post:
      tags:
        - Buildings
      summary: Add a new building
      requestBody:
        $ref: '#/components/requestBodies/building'
      responses:
        200:
          $ref: '#/components/responses/building'
        400:
          description: invalid bin format.
        401:
          description: unauthorized access.
        404:
          description: building not found.
  
  /buildings/{bin}:
    parameters:
      - $ref: '#/components/parameters/bin'
    get:
      tags:
        - Buildings
      summary: Get all information about a specific building
      responses:
        200:
          $ref: '#/components/responses/building'
    put:
      tags:
        - Buildings
      summary: Change information about a specific building.
      requestBody:
        $ref: '#/components/requestBodies/building'
      responses:
        200:
          $ref: '#/components/responses/building'
        400:
          description: invalid bin format.
        401:
          description: unauthorized access.
        404:
          description: building not found.
    delete:
      tags:
        - Buildings
      summary: Delete a building.
      responses:
        200:
          description: Successfully deleted.
    
  /buildings/{bin}/rooms:
    parameters:
      - $ref: '#/components/parameters/bin'
    get:
      tags:
        - Rooms
      summary: Get information about the rooms of a building
      operationId: getRooms
      responses:
        200:
          $ref: '#/components/responses/room'
    post:
      tags:
        - Rooms
      summary: Add a new room to a specified building
      requestBody:
        $ref: '#/components/requestBodies/roomRequestBody'
      responses:
        200:
          $ref: '#/components/responses/building'
          
  /building/{bin}/rooms/{rin}:
    parameters:
      - $ref: '#/components/parameters/bin'
      - $ref: '#/components/parameters/rin'
    get:
      tags:
        - Rooms
      summary: Get information about a specified room
      responses:
        200:
          $ref: '#/components/responses/room'
        400:
          description: invalid bin/rin format.
        401:
          description: unauthorized access.
        404:
          description: room not found.
    put:
      tags:
        - Rooms
      summary: Change information about a specific room.
      requestBody:
        $ref: '#/components/requestBodies/room'
      responses:
        200:
          $ref: '#/components/responses/room'
    delete:
      tags:
        - Rooms
      summary: Delete a room.
      responses:
        200:
          description: Successfully deleted.
          
  /buildings/{bin}/components:
    parameters:
      - $ref: '#/components/parameters/bin'
    get:
      tags:
        - Components
      summary: Get information about all components of a specific building.
      responses:
        200:
          $ref: '#/components/responses/component'
    post:
      tags: 
        - Components
      summary: Add a new component to a specific building.
      requestBody:
        $ref: '#/components/requestBodies/component'
      responses:
        200:
          $ref: '#/components/responses/building'
  
  /buildings/{bin}/rooms/{rin}/components:
    parameters:
      - $ref: '#/components/parameters/bin'
      - $ref: '#/components/parameters/rin'
    get:
      tags:
        - Components
      summary: Get information about all components of a specific room.
      responses:
        200:
          $ref: '#/components/responses/component'
    post:
      tags: 
        - Components
      summary: Add a new component to a specific room.
      requestBody:
        $ref: '#/components/requestBodies/component'
      responses:
        200:
          $ref: '#/components/responses/building'
  
  /buildings/{bin}/components/{cin}:
    parameters:
      - $ref: '#/components/parameters/bin'
      - $ref: '#/components/parameters/cin'
    put:
      tags:
        - Components
      summary: Change information about a specific Building Component.
      requestBody:
        $ref: '#/components/requestBodies/component'
      responses:
        200:
          $ref: '#/components/responses/component'
    delete:
      tags:
        - Components
      summary: Delete a building component.
      responses:
        200:
          description: Successfully deleted.
          
  /buildings/{bin}/rooms/{rin}/components/{cin}:
    parameters:
      - $ref: '#/components/parameters/bin'
      - $ref: '#/components/parameters/rin'
      - $ref: '#/components/parameters/cin'
    put:
      tags:
        - Components
      summary: Change information about a specific Room Component.
      requestBody:
        $ref: '#/components/requestBodies/component'
      responses:
        200:
          $ref: '#/components/responses/component'
    delete:
      tags:
        - Components
      summary: Delete a room component.
      responses:
        200:
          description: Successfully deleted.
  
  /buildings/{bin}/notifications:
    parameters:
    - $ref: '#/components/parameters/bin'
    post:
        tags: 
          - Notifications
        summary: Add a new notification to a specific building.
        requestBody:
          $ref: '#/components/requestBodies/notification'
        responses:
          200:
            $ref: '#/components/responses/building'
  
  /buildings/{bin}/notifications/{nin}:
    parameters:
      - $ref: '#/components/parameters/bin'
      - $ref: '#/components/parameters/nin'
    put:
      tags:
        - Notifications
      summary: Change information about a specific building notification.
      requestBody:
        $ref: '#/components/requestBodies/notification'
      responses:
        200:
          $ref: '#/components/responses/notification'
    get:
      tags:
        - Notifications
      summary: Get information about a specific notification of a building.
      responses:
        200:
            $ref: '#/components/responses/notification'
    delete:
      tags:
        - Notifications
      summary: Delete a building notification.
      responses:
        200:
          description: Successfully deleted.
          
  /buildings/{bin}/components/{cin}/notifications/{nin}:
    parameters:
      - $ref: '#/components/parameters/bin'
      - $ref: '#/components/parameters/cin'
      - $ref: '#/components/parameters/nin'
    put:
      tags:
        - Notifications
      summary: Change information about a building component notification.
      requestBody:
        $ref: '#/components/requestBodies/notification'
      responses:
        200:
          $ref: '#/components/responses/notification'
    delete:
      tags:
        - Notifications
      summary: Delete a building component notification.
      responses:
        200:
          description: Successfully deleted.
          
  /buildings/{bin}/rooms/{rin}/notifications/{nin}:
    parameters:
      - $ref: '#/components/parameters/bin'
      - $ref: '#/components/parameters/rin'
      - $ref: '#/components/parameters/nin'
    post:
      tags: 
        - Notifications
      summary: Add a new notification to a specific room.
      requestBody:
        $ref: '#/components/requestBodies/notification'
      responses:
        200:
          $ref: '#/components/responses/room'
    put:
      tags:
        - Notifications
      summary: Change information about a specific room notification.
      requestBody:
        $ref: '#/components/requestBodies/notification'
      responses:
        200:
          $ref: '#/components/responses/notification'
    get:
      tags:
        - Notifications
      summary: Get information about a specific notification of a room.
      responses:
        200:
            $ref: '#/components/responses/notification'
    delete:
      tags:
        - Notifications
      summary: Delete a room notification.
      responses:
        200:
          description: Successfully deleted.
          
  /buildings/{bin}/rooms/{rin}/components/{cin}/notifications/{nin}:
    parameters:
      - $ref: '#/components/parameters/bin'
      - $ref: '#/components/parameters/rin'
      - $ref: '#/components/parameters/cin'
      - $ref: '#/components/parameters/nin'
    delete:
      tags:
        - Notifications
      summary: Delete a room component notification.
      responses:
        200:
          description: Successfully deleted.
    put:
      tags:
        - Notifications
      summary: Change information about a specific room component notification.
      requestBody:
        $ref: '#/components/requestBodies/notification'
      responses:
        200:
          $ref: '#/components/responses/notification'
        
components:
  requestBodies:
    notification:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/notification'
            
    building:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/building'
            
    buildingIdentificationNumber:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/building/properties/aoNumber'
            
    room:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/room'
            
    roomRequestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/roomRequestBody'
            
    buildingName:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/building/properties/name'
            
    roomName:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/room/properties/name'
            
    roomIdentificationNumber:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/room/properties/aoNumber'
            
    component:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/component'
            
  responses:
    200:
      description: Successful operation.

    building:
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/building'
     
    room:
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/room'
            
    component:
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/component'
            
    notification:
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/notification'
            
  parameters:
    bin:
      in: path
      name: bin
      required: true
      description: The Building Identification Number (BIN) as unique number of a building.
      style: simple
      schema:
        $ref: '#/components/schemas/bin'
        
    rin:
      in: path
      name: rin
      required: true
      description: The Room Identification Number (RIN) as unique number of a room.
      style: simple
      schema:
        $ref: '#/components/schemas/rin'
        
    cin:
      in: path
      name: cin
      required: true
      description: The Component Identification Number (CIN) as unique number of a component.
      style: simple
      schema:
        $ref: '#/components/schemas/cin'
        
    nin:
      in: path
      name: nin
      required: true
      description: The Notification Identification Number (NIN) as unique number of a Notification.
      style: simple
      schema:
        $ref: '#/components/schemas/nin'
        
      
  schemas:
  # single values
    in:
      type: string
      minimum: 1
  
    bin:
      type: string
      example: b-432
      minimum: 1
      
    cin:
      type: string
      example: c-41
      minimum: 1
      
    rin:
      type: string
      example: r-516
      minimum: 1
      
    nin:
      type: string
      example: n-7
      minimum: 1
      
    aoNumber:
      type: string
      
    components:
      type: array
      items:
        $ref: '#/components/schemas/component'
          
    notifications:
      type: array
      items:
        $ref: '#/components/schemas/notification'
        
  # multi-value schemas
    building:
      type: object
      properties:
        name:
          type: string
          example: "Audimax"
        aoNumber:
          $ref: '#/components/schemas/aoNumber'
        numFloors:
          type: integer
          minimum: 1
          example: 3
        
        position:
          $ref: '#/components/schemas/position'
        
        campusLocation:
          type: string
          enum:
            - south_campus
            - north_campus
            - east_campus
            - west_campus
            
        components:
          $ref: '#/components/schemas/components'
          
        notifications:
          $ref: '#/components/schemas/notifications'
          
        rooms:
          type: array
          items:
            $ref: '#/components/schemas/room'
        bin:
          $ref: '#/components/schemas/bin'
            
    buildingItem:
      type: object
      properties:
        name: 
          type: string
        aoNumber:
          $ref: '#/components/schemas/aoNumber'
        self_uri:
          type: string
          format: uri
      example:
        name: 'Audimax'
        aoNumber: 30.95
        self_uri: '/buildings/Audimax(30.95)'
            
    room:
      type: object
      properties:
        name:
          type: string
          example: "Fritz-Haller-Hörsaal"
        aoNumber:
          $ref: '#/components/schemas/aoNumber'
        floor:
          type: integer
        category:
          type: string
          enum:
            - sports
            - cafeteria
            - restroom
            - restroom_handicapped
            - office
            - lecture_room
            - seminar_room
            - library
        components:
          $ref: '#/components/schemas/components'
          
        notifications:
          $ref: '#/components/schemas/notifications'
        rin:
          $ref: '#/components/schemas/rin'
        parent:
          $ref: '#/components/schemas/bin'
          
    position:
      type: object
      properties:
        lat:
          type: number
          minimum: -90
          maximum: 90
          example: -33.222042
        lon:
          type: number
          minimum: -180
          maximum: 180
          example: 38.432693
          
          
    roomRequestBody:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/room/properties/name'
        aoNumber:
          $ref: '#/components/schemas/room/properties/aoNumber'
        buildingAoNumber:
          $ref: '#/components/schemas/building/properties/aoNumber'
        
    notification:
      type: object
      properties:
        title:
          type: string
          example: "Aufzug kaputt"
        description:
          type: string
          example: "Aufzug fährt nur bis zum 3. Stock."
        date:
          type: string
          format: date
        nin:
          $ref: '#/components/schemas/nin'
        parent:
          $ref: '#/components/schemas/in'
    
    component:
      type: object
      properties:
        componentType:
          type: string
          enum:
            - elevator
            - ramp
          example: elevator
        cin:
          $ref: '#/components/schemas/cin'
        parent:
          $ref: '#/components/schemas/rin'
        notification:
          $ref: '#/components/schemas/notification'
        position:
          $ref: '#/components/schemas/position'
