openapi: 3.0.3
info:
  title: SmartCampus-Building Domain
  description: SmartCampus-Building Domain specified as REST-API
  version: 1.2.1

paths:

  /buildings:
    get:
      summary: List all buildings
      description: Lists all buildings located on KIT-Campus which are embedded in the domain database.
      tags:
        - Buildings
      responses:
        200:
          $ref: '#/components/responses/building'
        400:
          description: invalid request message framing.
        404:
          description: Requested data doesn't exist.
    post:
      summary: Create a building
      description: Creates a new building on KIT-Campus and adds it to the domain database.
      tags:
        - Buildings
      requestBody:
        $ref: '#/components/requestBodies/building'
      responses:
        200:
          $ref: '#/components/responses/building'
        400:
          description: invalid request message framing.
        401:
          description: unauthorized access.
        404:
          description: Requested data doesn't exist.
    put:
      summary: Update a building
      description: Updates a specific building in the domain database.
      tags:
        - Buildings
      requestBody:
        $ref: '#/components/requestBodies/building'
      responses:
        200:
          $ref: '#/components/responses/building'
        400:
          description: invalid request message framing.
        401:
          description: unauthorized access.
        404:
          description: Requested data doesn't exist.

  /buildings/{bin}:
    parameters:
      - $ref: '#/components/parameters/bin'
    get:
      summary: Get a building
      description: Gets a specific building from the domain database.
      tags:
        - Buildings
      responses:
        200:
          $ref: '#/components/responses/building'
        400:
          description: invalid request message framing.
        404:
          description: Requested data doesn't exist.

    delete:
      summary: Remove a building
      description: Removes a specific building from the domain database.
      tags:
        - Buildings
      responses:
        200:
          description: Successfully deleted.
        400:
          description: invalid request message framing.
        401:
          description: unauthorized access.
        404:
          description: Requested data doesn't exist.

  /buildings/{bin}/rooms:
    parameters:
      - $ref: '#/components/parameters/bin'
    get:
      summary: List rooms
      description: Lists a building's rooms.
      tags:
        - Rooms
      responses:
        200:
          $ref: '#/components/responses/room'
        400:
          description: invalid request message framing.
        404:
          description: Requested data doesn't exist.

  /rooms:
    post:
      summary: Create a room
      description: Creates a new room and adds it to domain database.
      tags:
        - Rooms
      requestBody:
        $ref: '#/components/requestBodies/room'
      responses:
        200:
          $ref: '#/components/responses/room'
        400:
          description: invalid request message framing.
        401:
          description: unauthorized access.
        404:
          description: Requested data doesn't exist.

    put:
      summary: Update a room
      description: Updates a specific room in the domain database.
      tags:
        - Rooms
      requestBody:
        $ref: '#/components/requestBodies/room'
      responses:
        200:
          $ref: '#/components/responses/room'
        400:
          description: invalid request message framing.
        401:
          description: unauthorized access.
        404:
          description: Requested data doesn't exist.

  /rooms/{rin}:
    parameters:
      - $ref: '#/components/parameters/rin'
    get:
      summary: Get a room
      description: Gets a specific room from the domain database.
      tags:
        - Rooms
      responses:
        200:
          $ref: '#/components/responses/room'
        400:
          description: invalid request message framing.
        404:
          description: Requested data doesn't exist.

    delete:
      summary: Remove a room
      description: Removes a specific room from the domain database.
      tags:
        - Rooms
      responses:
        200:
          description: Successfully deleted.
        400:
          description: invalid request message framing.
        401:
          description: unauthorized access.
        404:
          description: Requested data doesn't exist.

  /components:
    post:
      summary: Create a component
      description: Creates a new component and adds it to domain database.
      tags:
        - Components
      requestBody:
        $ref: '#/components/requestBodies/component'
      responses:
        200:
          $ref: '#/components/responses/component'
        400:
          description: invalid request message framing.
        401:
          description: unauthorized access.
        404:
          description: Requested data doesn't exist.

    put:
      summary: Update a component
      description: Updates a specific component in the domain database.
      tags:
        - Components
      requestBody:
        $ref: '#/components/requestBodies/component'
      responses:
        200:
          $ref: '#/components/responses/component'
        400:
          description: invalid request message framing.
        401:
          description: unauthorized access.
        404:
          description: Requested data doesn't exist.

  /buildings/{bin}/components:
    parameters:
      - $ref: '#/components/parameters/bin'
    get:
      summary: List components
      description: Lists a building's components.
      tags:
        - Components
      responses:
        200:
          $ref: '#/components/responses/component'
        400:
          description: invalid request message framing.
        404:
          description: Requested data doesn't exist.


  /rooms/{rin}/components:
    parameters:
      - $ref: '#/components/parameters/rin'
    get:
      summary: List components
      description: Lists a room's components.
      tags:
        - Components
      responses:
        200:
          $ref: '#/components/responses/component'
        400:
          description: invalid request message framing.
        404:
          description: Requested data doesn't exist.

  /components/{cin}:
    parameters:
      - $ref: '#/components/parameters/cin'
    get:
      summary: Get a component
      description: Gets a specific component from the domain database.
      tags:
        - Components
      responses:
        200:
          $ref: '#/components/responses/component'
        400:
          description: invalid request message framing.
        404:
          description: Requested data doesn't exist.

    delete:
      summary: Remove a component
      description: Removes a specific component from the domain database.
      tags:
        - Components
      responses:
        200:
          description: Successfully deleted.
        400:
          description: invalid request message framing.
        401:
          description: unauthorized access.
        404:
          description: Requested data doesn't exist.

  /notifications:
    post:
      summary: Create a notification
      description: Creates a new notifications and adds it to domain database.
      tags:
        - Notifications
      requestBody:
        $ref: '#/components/requestBodies/notification'
      responses:
        200:
          $ref: '#/components/responses/notification'
        400:
          description: invalid request message framing.
        401:
          description: unauthorized access.
        404:
          description: Requested data doesn't exist.

    put:
      summary: Update a notification
      description: Updates a specific notification in the domain database.
      tags:
        - Notifications
      requestBody:
        $ref: '#/components/requestBodies/notification'
      responses:
        200:
          $ref: '#/components/responses/notification'
        400:
          description: invalid request message framing.
        401:
          description: unauthorized access.
        404:
          description: Requested data doesn't exist.

  /buildings/{bin}/notifications:
    parameters:
      - $ref: '#/components/parameters/bin'
    get:
      summary: List notifications
      description: Lists a building's notifications.
      tags:
        - Notifications
      responses:
        200:
          $ref: '#/components/responses/notification'
        400:
          description: invalid request message framing.
        404:
          description: Requested data doesn't exist.

  /rooms/{rin}/notifications:
    parameters:
      - $ref: '#/components/parameters/rin'
    get:
      summary: List notifications
      description: Lists a room's notifications.
      tags:
        - Notifications
      responses:
        200:
          $ref: '#/components/responses/notification'
        400:
          description: invalid request message framing.
        404:
          description: Requested data doesn't exist.

  /components/{cin}/notifications:
    parameters:
      - $ref: '#/components/parameters/cin'
    get:
      summary: List notifications
      description: Lists a component's notifications.
      tags:
        - Notifications
      responses:
        200:
          $ref: '#/components/responses/notification'
        400:
          description: invalid request message framing.
        404:
          description: Requested data doesn't exist.

  /notifications/{nin}:
    parameters:
      - $ref: '#/components/parameters/nin'
    get:
      summary: Get a notification
      description: Gets a specific notification from the domain database.
      tags:
        - Notifications
      responses:
        200:
          $ref: '#/components/responses/notification'
        400:
          description: invalid request message framing.
        404:
          description: Requested data doesn't exist.

    delete:
      summary: Remove a notification
      description: Removes a specific notification from the domain database.
      tags:
        - Notifications
      responses:
        200:
          description: Successfully deleted.
        400:
          description: invalid request message framing.
        401:
          description: unauthorized access.
        404:
          description: Requested data doesn't exist.

components:

  requestBodies:

    notification:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/notification'

    building:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/building'

    room:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/room'

    component:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/component'

  responses:

    building:
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/building'

    notification:
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/notification'

    component:
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/component'

    room:
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/room'

  parameters:

    bin:
      in: path
      name: bin
      required: true
      description: The Building Identification Number (BIN) as unique number of a building.
      style: simple
      schema:
        $ref: '#/components/schemas/bin'

    rin:
      in: path
      name: rin
      required: true
      description: The Room Identification Number (RIN) as unique number of a room.
      style: simple
      schema:
        $ref: '#/components/schemas/rin'

    cin:
      in: path
      name: cin
      required: true
      description: The Component Identification Number (CIN) as unique number of a component.
      style: simple
      schema:
        $ref: '#/components/schemas/cin'

    nin:
      in: path
      name: nin
      required: true
      description: The Notification Identification Number (NIN) as unique number of a Notification.
      style: simple
      schema:
        $ref: '#/components/schemas/nin'

  schemas:

    # single value schemas

    bin:
      type: string
      example: "b-432"
      minimum: 1

    cin:
      type: string
      example: "c-41"
      minimum: 1

    rin:
      type: string
      example: "r-516"
      minimum: 1

    nin:
      type: string
      example: "n-7"
      minimum: 1

    # multi value schemas

    building:
      type: object
      properties:
        building_name:
          type: string
          example: "Audimax"
        building_number:
          type: string
          example: "30.95"
        num_floors:
          type: integer
          minimum: 1
          example: 3
        geographical_location:
          $ref: '#/components/schemas/geographical_location'
        campus_location:
          type: string
          enum:
            - south_campus
            - north_campus
            - east_campus
            - west_campus
        identification_number:
          $ref: '#/components/schemas/bin'

    room:
      type: object
      properties:
        room_name:
          type: string
          example: "Fritz-Haller-Hörsaal (HS 37)"
        room_number:
          type: string
          example: "001"
        floor:
          type: integer
          example: 0
        room_category:
          type: string
          enum:
            - sports
            - cafeteria
            - restroom
            - restroom_handicapped
            - office
            - lecture_room
            - seminar_room
            - library
        identification_number:
          $ref: '#/components/schemas/rin'
        parent_identification_number:
          $ref: '#/components/schemas/bin'
        geographical_location:
          $ref: '#/components/schemas/geographical_location'

    component:
      type: object
      properties:
        componentType:
          type: string
          enum:
            - elevator
            - ramp
          example: elevator
        component_description:
          type: string
          example: "Clock without pointer."
        identification_number:
          $ref: '#/components/schemas/nin'
        parent_identification_number:
          oneOf:
            - $ref: '#/components/schemas/rin'
            - $ref: '#/components/schemas/bin'
        geographical_location:
          $ref: '#/components/schemas/geographical_location'

    notification:
      type: object
      properties:
        notification_title:
          type: string
          example: "Elevator stuck"
        notification_description:
          type: string
          example: "Elevator is stuck in 3rd floor."
        creation_date:
          type: string
          format: date
        identification_number:
          $ref: '#/components/schemas/nin'
        parent_identification_number:
          oneOf:
            - $ref: '#/components/schemas/bin'
            - $ref: '#/components/schemas/rin'
            - $ref: '#/components/schemas/cin'

    geographical_location:
      type: object
      properties:
        latitude:
          type: number
          minimum: -90
          maximum: 90
          example: -33.222042
        longitude:
          type: number
          minimum: -180
          maximum: 180
          example: 38.432693
